### ISSUE TITLE
More 1.8 features

### ISSUE THREAD

**Issue by Johandrex** [Acquized/Aero#1]
Could you add a option to bring back 1.8 Armor strength, Swords/other tools damages & OP Apple effects?

**Comment by Acquized** [comment]
Added to ToDo List for 1.3. Expect a Commit tommorow and a release (if it works).

**Comment by Johandrex** [comment]
Awesome, I can't see it yet though

**Comment by Acquized** [comment]
Yea, i currently have problems with it causing the complete Server to crash. When i fixed the crash issue, i will release it.

**Comment by Johandrex** [comment]
Alright but if you fix it within 2 days I'll gladly donate 10 USD after that I know that it's working as expected. I'd also like a new option added so lapis is autoadded in Enchantment tables. And I want "UserColliding: false" fixed as it doesn't seem to work, could this also stop mobs to collide as it's causing CPU loss.

**Comment by Acquized** [comment]
Auto Lapis in Enchantment Tables will be added in 1.4.
User Colliding has been fixed & Old Sword and Axe Damage has been added right now. The Mob Colliding is currently without in deep Changes in the Server Software not possibile, as Mojang doesn't hasn't added a Feature to stop it. You can test the pre release [here](https://github.com/Acquized/Aero/releases/download/1.3/Aero.jar). I will release a full Version once i have finished testing it.

**Comment by Johandrex** [comment]
Could you add the old damage to all tools?
And the mob colliding isn't super important, but the player pushing colliding still doesn't work.
Armor strength + op apples effects are coming too right?

**Comment by Acquized** [comment]
Added to ToDo List, thanks for the suggestion, i'm looking into it asap.

**Comment by Johandrex** [comment]
Any new pre-release coming soon?

**Comment by Johandrex** [comment]
It was 9 days since you made any commits to the source. I'm willing to double the offer to 20 USD if you update the plugin within 3 days. I really need this plugins updated.

**Comment by Acquized** [comment]
I didn't update the source but you can decompile the Pre Releases (releases tab), there i post it. Currently its easter so i have no school, so i have enough time to do it. Expect a **PreRelease** (not commit) soon.

**Comment by Acquized** [comment]
Pre Release `pre1.3b` has been released including restoring of the old Notch Apple Effects. Please report any bugs here to me. Download it [here](https://github.com/Acquized/Aero/releases/tag/pre1.3).

**Comment by Johandrex** [comment]
That's not how 1.8 OP Apples were, you can't brew at all, the tools doesn't have 1.8 damage, the player colission is still not fixed, the anti-knockback still happens sometimes, the armor doesn't have the same strength and the lapis isn't being put in the enchant table

**Comment by Johandrex** [comment]
only getting one error: http://hastebin.com/atisovefij.avrasm

**Comment by Acquized** [comment]
How were the 1.8 OP Apples? I have looked up the History in the Minecraft Wiki and there it were, the Swords and Axes should make the 1.8 Damage (it will not be displayed in lore currently), i haven't implemented the Armor yet and what do you mean with Anti-Knockback? The Lapis Exception should be fixed soon.

**Comment by Johandrex** [comment]
Op apples had
Absorption - 2:00
Resistance - 5:00
Regeneration - 0:30
Fire Resistance - 5:00

The swords & axes are fine, I ment the other tools too though as some of the tools have different enchants on my Faction server.

Some players randomly have anti-knockback (tested with alt) after that the player-colission were turned off on the plugin

**Comment by Acquized** [comment]
I will correct the Notch Apples, also i will add Shovels and Pickaxes soon. I currently can't reconstruct the Anti Knockback Issue, could you make a Video?

**Comment by Johandrex** [comment]
Sure

**Comment by Johandrex** [comment]
Nevermind about the anti-knockback issue sorry..

**Comment by Acquized** [comment]
Ok, no problem.

**Comment by Johandrex** [comment]
Closed, no longer needed as it's taking too long time. I've gotten another developer that fixed everything in less than 24 hours.
